### ISSUE TITLE
素数でない値が素数と判定される事がある

### ISSUE THREAD

**Issue by habu1010** [rotildeof/mathfunction#2]
is_primeの、以下の部分において、
https://github.com/rotildeof/mathfunction/blob/50ecd39394f63e48d12c565e834cd9c007811b15/mathfunction.cxx#L81
`i * i <= n`とすべきところを`i * i < n`としてしまっているため、`5+6n (n>=0)`が素数の時にその2乗の値も誤って素数と判定されてしまっています。

**Comment by rotildeof** [comment]
ご指摘ありがとうございます〜〜。気づきませんでした。
